name: Maven Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    # Run tests every day to capture changes in ::gentoo and upstream changes
    # in artifacts being tested that cause tests to fail as soon as possible
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Set up master ::gentoo
      run: |
        ./.github/workflow-scripts/setup-master-gentoo.sh
    - name: Set up Portage
      run: |
        ./.github/workflow-scripts/setup-portage.sh
    - name: Test Maven project
      run: |
        mvn -q test
